namespace WpfOCR;

/// <summary>
/// 界面中英文：zh / en。键用短 id，缺键时回退中文再回退键名。
/// </summary>
static class Loc {
	public const string Zh = "zh";
	public const string En = "en";

	static string lang = Zh;

	public static string Lang {
		get => lang;
		set {
			var v = (value ?? "").Trim().ToLowerInvariant();
			if (v is "en" or "en-us" or "english") lang = En;
			else lang = Zh;
		}
	}

	public static bool IsEn => lang == En;
	public static bool IsZh => lang != En;

	public static string T(string key) {
		if (string.IsNullOrEmpty(key)) return "";
		if (IsEn && EnMap.TryGetValue(key, out var en) && !string.IsNullOrEmpty(en))
			return en;
		if (ZhMap.TryGetValue(key, out var zh) && !string.IsNullOrEmpty(zh))
			return zh;
		return key;
	}

	public static string T(string key, params object[] args) {
		try { return string.Format(T(key), args); }
		catch { return T(key); }
	}

	public static void SetFromConfig(string uiLang) => Lang = uiLang;

	// ───────── 中文 ─────────
	static readonly Dictionary<string, string> ZhMap = new(StringComparer.OrdinalIgnoreCase) {
		// 窗口 / 通用
		["app.title"] = "WpfOCR — 截图识别",
		["app.brand"] = "截图识别",
		["ready"] = "就绪",
		["ok"] = "确定",
		["cancel"] = "取消",
		["copy"] = "复制",
		["settings"] = "参数设置",
		["language"] = "界面语言",

		// 菜单顶
		["menu.file"] = "文件(_F)",
		["menu.capture"] = "截图(_C)",
		["menu.edit"] = "编辑(_E)",
		["menu.tools"] = "工具(_T)",
		["menu.lang"] = "界面语言(_L)",
		["menu.lang.zh"] = "中文",
		["menu.lang.en"] = "English",

		// 文件
		["menu.paste"] = "粘贴图片(_V)",
		["menu.paste.tip"] = "从剪贴板粘贴图片",
		["menu.copyfile"] = "复制文件(_S)",
		["menu.copyfile.tip"] = "复制为文件到剪贴板，可在资源管理器 Ctrl+V 粘贴",
		// 保存当前图片到本地文件（与 menu.copyfile 不同）
		["menu.saveimg"] = "保存图片(_S)",
		["menu.saveimg.tip"] = "将当前图片保存为 PNG/JPEG/BMP 文件",
		["menu.pdf"] = "PDF 识别工作台(_P)…",
		["menu.pdf.tip"] = "识别、编辑、存草稿、导出可检索 PDF",
		["menu.exit"] = "退出(_X)",

		// 截图
		["menu.ocr"] = "截图识别(_O)",
		["menu.ocr.tip"] = "区域截图并识别文字",
		["menu.snap"] = "截图标注(_A)",
		["menu.snap.tip"] = "微信式截图：框选 / 标注 / 复制 / 保存",
		["menu.board"] = "屏幕画板(_B)",
		["menu.board.tip"] = "截取全屏静止画面，直接画图标注（画笔/框/箭头/文字）",
		["menu.voice"] = "语音输入(_V)",
		["menu.voice.tip"] = "麦克风听写注入焦点窗口；再按一次结束",
		["menu.longshot"] = "长截图(_L)…",
		["menu.longshot.tip"] = "点选窗口后自动滚动拼接长图（仅截图，不 OCR）",
		["menu.snapshots"] = "截图历史(_H)",
		["menu.snapshots.tip"] = "打开 screenshots 截图历史文件夹",
		["menu.snapcopyimg"] = "截图完成 · 复制为图片",
		["menu.snapcopyfile"] = "截图完成 · 复制为文件",
		["menu.snapcopypath"] = "截图完成 · 复制为文件路径",
		["menu.record"] = "录屏(_R)…",
		["menu.record.tip"] = "点选/框选区域后录制 MP4",
		["menu.recordopt"] = "录屏选项(_E)…",
		["menu.recordopt.tip"] = "编码 / 帧率 / CRF / 最大宽高",
		["menu.gifrecord"] = "GIF录屏(_G)…",
		["menu.gifrecord.tip"] = "点选/框选区域后录制低帧率无声 GIF",
		["menu.gifrecordopt"] = "GIF录屏选项(_F)…",
		["menu.gifrecordopt.tip"] = "帧率 / 最大宽高",

		// 编辑
		["menu.copytext"] = "复制文字(_T)",
		["menu.copytext.tip"] = "有图上选区时复制选中行，否则复制全部结果",
		["menu.copyimg"] = "复制图片(_I)",
		["menu.copyimg.tip"] = "将当前图片以文件形式复制到剪贴板（可粘贴到资源管理器）",
		["menu.toggletext"] = "显示文字叠加(_W)",
		["menu.toggletext.tip"] = "叠加识别文字（Umi 黑底白字）；在文字上拖选",
		["menu.cancelocr"] = "取消识别(_N)",
		["menu.cancelocr.tip"] = "取消当前识别（推理中可能需等本轮结束）",

		// 工具
		["menu.settings"] = "参数设置(_S)…",
		["menu.settings.tip"] = "检测阈值、热键、HTTP、PDF 等",
		["menu.install"] = "安装功能(_I)…",
		["menu.install.tip"] = "安装 OCR/ASR 模型、GPU、核显等（中文系统优先国内镜像）",
		["menu.diag"] = "诊断(_D)…",
		["menu.diag.tip"] = "CUDA / DirectML / 路径 / 显示器 DPI",
		["menu.update"] = "检查更新(_U)…",
		["menu.update.tip"] = "从 GitHub Releases 检查并下载更新",
		["menu.about"] = "关于(_A)…",
		["menu.about.tip"] = "版本与许可证",
		["update.title"] = "检查更新",
		["update.checking"] = "正在检查更新…",
		["update.downloading"] = "正在下载更新包…",
		["update.preparing"] = "正在准备安装更新…",
		["update.working"] = "处理中…",
		["update.done"] = "完成",
		["update.error"] = "更新失败",
		["update.cancelling"] = "正在取消…",
		["update.latest"] = "当前已是最新版本。\n\n当前：{0}\n线上：{1}",
		["update.found"] = "发现新版本，是否下载并安装？\n\n当前：{0}\n最新：{1}\n文件：{2}\n大小：{3}\n\n安装时将退出程序并自动重启。",
		["update.fail"] = "检查/下载更新失败：\n{0}",
		["about.title"] = "关于 WpfOCR",
		["about.version"] = "版本 {0}",
		["about.copyright"] = "Copyright (c) 2026 WpfOCR Contributors · MIT License",
		["about.license_head"] = "许可证（MIT）",
		["about.third"] = "第三方说明…",
		["about.open_lic"] = "打开 LICENSE",
		["about.file_missing"] = "未找到该文件（请确认已随程序复制 LICENSE / THIRD_PARTY_NOTICES.md）。",
		["about.license_fallback"] =
			"MIT License\n\nCopyright (c) 2026 WpfOCR Contributors\n\n" +
			"Permission is hereby granted, free of charge, to any person obtaining a copy of this software " +
			"and associated documentation files (the \"Software\"), to deal in the Software without restriction...\n\n" +
			"完整正文见程序目录 LICENSE。第三方组件见 THIRD_PARTY_NOTICES.md。",

		// 顶栏
		["label.pack"] = "模型",
		["label.variant"] = "语言",
		["label.device"] = "设备",
		["label.detlen"] = "边长",
		["label.pack.tip"] = "模型包",
		["label.variant.tip"] = "语言 / 模型变体",
		["label.device.tip"] = "推理设备：NVIDIA GPU / 核显 DirectML / CPU",
		["label.detlen.tip"] = "检测边长上限：越大越准越慢，大图/拼图建议 1600+",
		["device.gpu"] = "GPU",
		["device.igpu"] = "核显",
		["device.cpu"] = "CPU",
		["device.gpu.tip"] = "NVIDIA CUDA",
		["device.igpu.tip"] = "Intel 核显等 DirectML 加速",

		// 主 Tab
		["tab.ocr"] = "截图识别",
		["tab.tts"] = "语音合成",

		// 工具栏
		["tb.ocr"] = "截图识别",
		["tb.ocr.tip"] = "区域截图并识别",
		["tb.snap"] = "截图标注",
		["tb.snap.tip"] = "微信式截图标注",
		["tb.board"] = "屏幕画板",
		["tb.board.tip"] = "全屏冻结后画图标注",
		["tb.paste"] = "粘贴",
		["tb.paste.tip"] = "粘贴图片 (Ctrl+V)",
		["tb.copyimg"] = "复制图",
		["tb.copyimg.tip"] = "以文件形式复制当前图片（可粘贴到资源管理器）",
		["tb.copyfile"] = "复制文件",
		["tb.copyfile.tip"] = "复制为文件到剪贴板，可在资源管理器 Ctrl+V 粘贴",
		["tb.save"] = "保存",
		["tb.save.tip"] = "将当前图片保存到文件",
		["tb.pdf"] = "PDF",
		["tb.pdf.tip"] = "PDF 识别工作台",
		["tb.record"] = "录屏",
		["tb.record.tip"] = "点选/框选区域后录制 MP4",
		["tb.recordopt"] = "录屏选项",
		["tb.recordopt.tip"] = "编码 / 帧率 / CRF / 音频 / 最大宽高",
		["tb.settings"] = "参数设置",
		["tb.settings.tip"] = "检测阈值、热键、HTTP、PDF 等",
		["tb.text"] = "文字",
		["tb.text.tip"] = "叠加识别文字；在文字上拖选",
		["img.size.tip"] = "图片原始分辨率（像素）",
		["img.zoom.tip"] = "当前缩放",

		// 图区 / 结果
		["hint.empty"] = "菜单「截图」识别 / 标注 ·「文件」粘贴 / PDF\n也可拖入图片 · 滚轮缩放 · 文字拖选 · Ctrl+C 复制",
		["result.title"] = "识别结果",
		["result.tab.ocr"] = "OCR",
		["result.tab.qr"] = "条码",
		["result.running"] = "识别中",
		["result.meta"] = "推理 — · 端到端 — | 置信度 —",
		["result.qr.meta"] = "条码 —",
		["result.qr.empty"] = "（未检出条码/二维码）",
		["ocr.running"] = "正在识别中…",
		["ocr.running.hint"] = "检测 · 方向 · 识别",
		["qr.running"] = "正在识别条码…",
		["qr.running.hint"] = "QR · EAN · Code128 · DataMatrix …",
		["ocr.cancel"] = "取消识别",
		["ocr.cancel.tip"] = "取消当前识别（推理中可能需等本轮结束）",
		["copy.tip"] = "有图上选区时复制选中行，否则复制全部结果 (Ctrl+C)",

		// 状态
		["st.ready_hotkeys"] = "就绪 · 呼出 {0} · 标注 {1} · 截图识别 {2} · 语音 {3} · 实时字幕 {4}",
		["st.voice_on"] = "语音输入已开始 · 再按 {0} 结束",
		["st.voice_off"] = "语音输入已结束",
		["st.live_on"] = "实时字幕已开始 · 再按 {0} 结束",
		["st.live_off"] = "实时字幕已结束",
		["st.http_ok"] = "HTTP API · http://{0}:{1}/api/ocr",
		["st.http_fail"] = "HTTP 启动失败: {0}",
		["st.http_init_fail"] = "HTTP 服务初始化失败: {0}",
		["st.tray_fail"] = "托盘图标失败: {0}",
		["st.hotkey_fail"] = "热键初始化失败: {0}",
		["st.hotkey_toggle_fail"] = "热键切换窗口失败: {0}",
		["st.ocr_busy"] = "正在识别中…",
		["st.clip_ocr"] = "托盘 · 从剪贴板识别…",
		["st.clip_fail"] = "剪贴板识别失败: {0}",
		["st.detlen"] = "检测边长上限 → {0}（下次识别生效）",
		["st.switched"] = "已切换 · {0} · {1} · 边长{2}，下次识别时加载",
		["st.warmup"] = "{0} · 正在预热引擎…",
		["st.warmup_ok"] = "{0} · 已预热 · {1} · {2} · 加载 {3}ms",
		["st.warmup_stay"] = "{0} · 引擎常驻 · {1} · {2}",
		["st.warmup_fail"] = "{0} · 预热失败: {1}",
		["st.sel_drag"] = "选区 · 拖动扩展 · Ctrl+C 复制",
		["st.sel_chars"] = "已选中 {0} 字 · Ctrl+C 复制",
		["st.sel_all"] = "已全选 {0} 字 · Ctrl+C 复制",
		["st.sel_clear"] = "已取消选区",
		["st.no_text"] = "没有可复制的文字",
		["st.copy_fail"] = "复制失败: {0}",
		["st.snap_recopy_img"] = "已重新复制为图片 · {0}",
		["st.snap_recopy_file"] = "已重新复制为文件 · {0}",
		["st.snap_recopy_path"] = "已重新复制为路径 · {0}",
		["st.snap_recopy_none"] = "暂无截图可重新复制",
		["st.snap_recopy_fail"] = "重新复制失败: {0}",
		["st.capture_cancel"] = "已取消截图",
		["st.capture_ocr"] = "截图 {0}×{1} · 识别中…",
		["st.capture_fail"] = "截图识别失败: {0}",
		["st.record_opt"] = "录屏选项已保存 · {0}",
		["st.record_busy"] = "请等待当前截图/录屏结束",
		["st.record_pick"] = "录屏 · 请单击窗口或拖拽框选区域…",
		["st.record_cancel"] = "已取消录屏",
		["st.record_region"] = "录屏区域 {0}×{1} · {2} · {3}fps · {4}",
		["st.record_saved"] = "录屏已保存: {0}",
		["st.record_end"] = "录屏已结束（未保存）",
		["st.record_fail"] = "录屏失败: {0}",
		["st.longshot"] = "长截图 · 请单击目标窗口…",
		["st.longshot_cancel"] = "已取消长截图",
		["st.lang"] = "界面语言 → {0}",
		["msg.capture"] = "截图识别",
		["msg.record"] = "录屏",
		["msg.recordopt"] = "录屏选项",

		// 托盘
		["tray.show"] = "显示主窗口",
		["tray.ocr"] = "截图识别",
		["tray.snap"] = "截图标注",
		["tray.board"] = "屏幕画板",
		["tray.voice"] = "语音输入",
		["tray.clip"] = "从剪贴板识别",
		["tray.clipfile"] = "复制剪贴板图片为文件",
		["tray.pdf"] = "PDF 识别工作台…",
		["tray.snapshots"] = "截图历史",
		["tray.snapcopyimg"] = "截图完成 · 复制为图片",
		["tray.snapcopyfile"] = "截图完成 · 复制为文件",
		["tray.snapcopypath"] = "截图完成 · 复制为文件路径",
		["tray.record"] = "录屏",
		["tray.recordopt"] = "录屏选项…",
		["tray.gifrecord"] = "GIF录屏",
		["tray.gifrecordopt"] = "GIF录屏选项…",
		["tray.settings"] = "参数设置…",
		["tray.exit"] = "退出",
		["tray.tip"] = "WpfOCR",

		// 设置窗（常用）
		["set.title"] = "参数设置",
		["set.tab.general"] = "常规",
		["set.tab.ocr"] = "识别",
		["set.tab.hotkey"] = "热键",
		["set.tab.asr"] = "语音",
		["set.tab.snap"] = "截图",
		["set.tab.http"] = "接口",
		["set.pack"] = "模型包",
		["set.variant"] = "语言 / 模型变体",
		["set.device"] = "推理设备",
		["set.device.gpu"] = "GPU (NVIDIA CUDA)",
		["set.device.igpu"] = "核显 (Intel DirectML)",
		["set.device.cpu"] = "CPU",
		["set.device.hint"] = "核显走 DirectML；与 NVIDIA CUDA 不能同进程切换，换设备若失败请重启程序",
		["set.detlen"] = "检测边长上限",
		["set.detlen.hint"] = "也可在主窗口顶栏「边长」快速切换",
		["set.detth"] = "检测阈值",
		["set.boxth"] = "框置信阈值",
		["set.cls"] = "启用方向分类 (cls)",
		["set.service"] = "服务模式（引擎常驻预热，不释放模型内存）",
		["set.service.hint"] = "启用后启动与改参会立即加载引擎并保持常驻；关闭则为懒加载（改参后丢弃，下次识别再加载）",
		["set.pdf"] = "PDF 识别",
		["set.pdf.text"] = "导出时叠加不可见文字层（可检索/可复制）",
		["set.pdf.hint"] = "页面尺寸按原 PDF 页面还原；光栅化 DPI 由程序固定（约 150），无需配置",
		["set.hotkey"] = "全局热键",
		["set.hotkey.hint"] = "点「捕获」后按下组合键写入；「清空」禁用该热键。留空亦可手改。",
		["set.hotkey.main"] = "主窗呼出/隐藏 · 默认 Ctrl+Alt+O；留空禁用。再按一次隐藏",
		["set.hotkey.snap"] = "截图标注 · 框选并标注，默认 Ctrl+Alt+Q；留空禁用",
		["set.hotkey.ocr"] = "截图识别 · 框选后立即 OCR，默认 Ctrl+Alt+W；留空禁用",
		["set.hotkey.board"] = "屏幕画板 · 全屏冻结后标注；默认空=禁用",
		["set.hotkey.voice"] = "语音输入 · 麦克风听写注入焦点窗口，默认 Ctrl+Alt+V；再按结束；留空禁用",
		["set.hotkey.live"] = "系统实时字幕 · 流式识别到桌面字幕窗，默认 Ctrl+Alt+B；再按结束；留空禁用",
		["set.lang"] = "界面语言",
		["set.lang.hint"] = "切换后立即生效，并写入 config.toml",
		["set.tray"] = "最小化时隐藏到通知栏（关闭需确认退出）",
		["set.log"] = "系统日志",
		["set.log.enable"] = "写入诊断日志（默认关闭）",
		["set.log.hint"] = "开启后写入 log/capture.log 与录屏 log/record_*.log，便于排查；日常使用请保持关闭",
		["set.http"] = "HTTP 识图 API（Umi 兼容）",
		["set.http.hint"] = "POST /api/ocr · 支持 JSON base64 与 multipart 上传；GET /api/ocr/get_options",
		["set.http.enable"] = "启用 HTTP API",
		["set.http.host"] = "监听地址",
		["set.http.port"] = "端口",
		["set.asr.mode"] = "语音输入模型",
		["set.asr.mode.hint"] = "流式：边说边出字。离线：整段录音，停止后一次性识别。勾选自动分句时，识别出一句立即润色并输出。",
		["set.asr.mode.stream"] = "流式模型（边说边出）",
		["set.asr.mode.offline"] = "离线模型（停止后一次性输出）",
		["set.asr.voice.polish"] = "语音输入润色",
		["set.asr.voice.split"] = "语音输入自动分句",
		["set.asr.voice.split.tip"] = "识别出一句立即润色（若已勾选润色）并输入到焦点窗口",
		["set.asr.voice.split.sec"] = "自动分句间隔（秒）",
		["set.asr.voice.split.sec.tip"] = "静音达到此时长才切一句，连续说话不切；1–30，默认 5",
		["set.asr.live"] = "实时字幕模型",
		["set.asr.live.hint"] = "流式：边说边出字幕。离线：按静音切句后整句识别，可更准但延迟更大。",
		["set.asr.live.stream"] = "流式模型",
		["set.asr.live.offline"] = "离线模型（静音切句）",
		["set.asr.live.polish"] = "实时字幕润色",
		["set.asr.live.split"] = "润色自动分句",
		["set.asr.llm"] = "润色（OpenAI 兼容）",
		["set.asr.llm.hint"] = "上方勾选润色且 URL、模型 id 都填才请求。听写在句末/停止后；实时字幕在每句完成后。会附带本轮已输出上文（约千字内）以便纠正同音与指代。Token 本地服务可留空。",
		["set.asr.llm.url"] = "API URL",
		["set.asr.llm.token"] = "Token",
		["set.asr.llm.model"] = "模型 id",
		["set.asr.llm.prompt"] = "润色提示词",
		["set.ok"] = "保存",
		["set.cancel"] = "取消",
	};

	// ───────── English ─────────
	static readonly Dictionary<string, string> EnMap = new(StringComparer.OrdinalIgnoreCase) {
		["app.title"] = "WpfOCR — Screenshot OCR",
		["app.brand"] = "Screenshot OCR",
		["ready"] = "Ready",
		["ok"] = "OK",
		["cancel"] = "Cancel",
		["copy"] = "Copy",
		["settings"] = "Settings",
		["language"] = "UI language",

		["menu.file"] = "_File",
		["menu.capture"] = "_Capture",
		["menu.edit"] = "_Edit",
		["menu.tools"] = "_Tools",
		["menu.lang"] = "_Language",
		["menu.lang.zh"] = "中文",
		["menu.lang.en"] = "English",

		["menu.paste"] = "Paste image(_V)",
		["menu.paste.tip"] = "Paste image from clipboard",
		["menu.copyfile"] = "Copy as file(_S)",
		["menu.copyfile.tip"] = "Copy as file to clipboard; paste in Explorer with Ctrl+V",
		["menu.saveimg"] = "Save image(_S)",
		["menu.saveimg.tip"] = "Save current image as PNG/JPEG/BMP",
		["menu.pdf"] = "PDF workbench(_P)…",
		["menu.pdf.tip"] = "OCR, edit, draft, export searchable PDF",
		["menu.exit"] = "E_xit",

		["menu.ocr"] = "Screenshot OCR(_O)",
		["menu.ocr.tip"] = "Capture a region and run OCR",
		["menu.snap"] = "Screenshot annotate(_A)",
		["menu.snap.tip"] = "WeChat-style capture: select / annotate / copy / save",
		["menu.board"] = "Screen board(_B)",
		["menu.board.tip"] = "Freeze full screen and draw/annotate (pen / shapes / text)",
		["menu.voice"] = "Voice input(_V)",
		["menu.voice.tip"] = "Dictate into the focused window; press again to stop",
		["menu.longshot"] = "Long screenshot(_L)…",
		["menu.longshot.tip"] = "Pick a window and auto-scroll stitch (image only, no OCR)",
		["menu.snapshots"] = "Screenshot history(_H)",
		["menu.snapshots.tip"] = "Open the screenshots history folder",
		["menu.snapcopyimg"] = "On capture · copy as image",
		["menu.snapcopyfile"] = "On capture · copy as file",
		["menu.snapcopypath"] = "On capture · copy as file path",
		["menu.record"] = "Screen record(_R)…",
		["menu.record.tip"] = "Pick window or region, record MP4",
		["menu.recordopt"] = "Record options(_E)…",
		["menu.recordopt.tip"] = "Codec / FPS / CRF / max size",
		["menu.gifrecord"] = "GIF record(_G)…",
		["menu.gifrecord.tip"] = "Pick window or region, low-FPS silent GIF",
		["menu.gifrecordopt"] = "GIF record options(_F)…",
		["menu.gifrecordopt.tip"] = "FPS / max size",

		["menu.copytext"] = "Copy text(_T)",
		["menu.copytext.tip"] = "Copy selection on image, or all results",
		["menu.copyimg"] = "Copy image(_I)",
		["menu.copyimg.tip"] = "Copy current image as file to clipboard (paste in Explorer)",
		["menu.toggletext"] = "Show text overlay(_W)",
		["menu.toggletext.tip"] = "Overlay OCR text; drag to select on text",
		["menu.cancelocr"] = "Cancel OCR(_N)",
		["menu.cancelocr.tip"] = "Cancel current OCR (may wait for current step)",

		["menu.settings"] = "_Settings…",
		["menu.settings.tip"] = "Thresholds, hotkeys, HTTP, PDF…",
		["menu.install"] = "_Install features…",
		["menu.install.tip"] = "Install OCR/ASR models, GPU, iGPU (CN systems prefer domestic mirrors)",
		["menu.diag"] = "_Diagnostics…",
		["menu.diag.tip"] = "CUDA / DirectML / paths / display DPI",
		["menu.update"] = "Check for _Updates…",
		["menu.update.tip"] = "Check and download updates from GitHub Releases",
		["menu.about"] = "_About…",
		["menu.about.tip"] = "Version and license",
		["update.title"] = "Check for Updates",
		["update.checking"] = "Checking for updates…",
		["update.downloading"] = "Downloading update package…",
		["update.preparing"] = "Preparing to install…",
		["update.working"] = "Working…",
		["update.done"] = "Done",
		["update.error"] = "Update failed",
		["update.cancelling"] = "Cancelling…",
		["update.latest"] = "You are already on the latest version.\n\nCurrent: {0}\nOnline: {1}",
		["update.found"] = "A new version is available. Download and install?\n\nCurrent: {0}\nLatest: {1}\nFile: {2}\nSize: {3}\n\nThe app will exit and restart automatically.",
		["update.fail"] = "Failed to check/download update:\n{0}",
		["about.title"] = "About WpfOCR",
		["about.version"] = "Version {0}",
		["about.copyright"] = "Copyright (c) 2026 WpfOCR Contributors · MIT License",
		["about.license_head"] = "License (MIT)",
		["about.third"] = "Third-party…",
		["about.open_lic"] = "Open LICENSE",
		["about.file_missing"] = "File not found. Ensure LICENSE / THIRD_PARTY_NOTICES.md is next to the exe.",
		["about.license_fallback"] =
			"MIT License\n\nCopyright (c) 2026 WpfOCR Contributors\n\n" +
			"Permission is hereby granted, free of charge, to any person obtaining a copy of this software " +
			"and associated documentation files (the \"Software\"), to deal in the Software without restriction...\n\n" +
			"Full text: LICENSE next to the executable. Third-party: THIRD_PARTY_NOTICES.md.",

		["label.pack"] = "Pack",
		["label.variant"] = "Lang",
		["label.device"] = "Device",
		["label.detlen"] = "Det",
		["label.pack.tip"] = "Model pack",
		["label.variant.tip"] = "Language / model variant",
		["label.device.tip"] = "Device: NVIDIA GPU / iGPU DirectML / CPU",
		["label.detlen.tip"] = "Detection side limit: larger = better & slower",
		["device.gpu"] = "GPU",
		["device.igpu"] = "iGPU",
		["device.cpu"] = "CPU",
		["device.gpu.tip"] = "NVIDIA CUDA",
		["device.igpu.tip"] = "Intel iGPU via DirectML",

		["tab.ocr"] = "Screenshot OCR",
		["tab.tts"] = "Speech",

		["tb.ocr"] = "OCR",
		["tb.ocr.tip"] = "Region capture + OCR",
		["tb.snap"] = "Annotate",
		["tb.snap.tip"] = "Screenshot annotate",
		["tb.board"] = "Board",
		["tb.board.tip"] = "Freeze screen and draw",
		["tb.paste"] = "Paste",
		["tb.paste.tip"] = "Paste image (Ctrl+V)",
		["tb.copyimg"] = "Copy img",
		["tb.copyimg.tip"] = "Copy current image as file (paste in Explorer)",
		["tb.copyfile"] = "Copy file",
		["tb.copyfile.tip"] = "Copy as file to clipboard; paste in Explorer with Ctrl+V",
		["tb.save"] = "Save",
		["tb.save.tip"] = "Save current image to file",
		["tb.pdf"] = "PDF",
		["tb.pdf.tip"] = "PDF workbench",
		["tb.record"] = "Record",
		["tb.record.tip"] = "Pick window/region and record MP4",
		["tb.recordopt"] = "Rec options",
		["tb.recordopt.tip"] = "Codec / FPS / CRF / audio / max size",
		["tb.settings"] = "Settings",
		["tb.settings.tip"] = "Thresholds, hotkeys, HTTP, PDF…",
		["tb.text"] = "Text",
		["tb.text.tip"] = "Text overlay; drag-select on text",
		["img.size.tip"] = "Image resolution (px)",
		["img.zoom.tip"] = "Zoom",

		["hint.empty"] = "Capture menu: OCR / annotate · File: paste / PDF\nDrop image · wheel zoom · select text · Ctrl+C copy",
		["result.title"] = "Results",
		["result.tab.ocr"] = "OCR",
		["result.tab.qr"] = "Barcode",
		["result.running"] = "OCR…",
		["result.meta"] = "Infer — · E2E — | Conf —",
		["result.qr.meta"] = "Barcode —",
		["result.qr.empty"] = "(No barcode / QR found)",
		["ocr.running"] = "Running OCR…",
		["ocr.running.hint"] = "Detect · CLS · Recognize",
		["qr.running"] = "Scanning barcodes…",
		["qr.running.hint"] = "QR · EAN · Code128 · DataMatrix …",
		["ocr.cancel"] = "Cancel",
		["ocr.cancel.tip"] = "Cancel current OCR (may wait for current step)",
		["copy.tip"] = "Copy selection on image, or all results (Ctrl+C)",

		["st.ready_hotkeys"] = "Ready · show {0} · annotate {1} · OCR {2} · voice {3} · live caption {4}",
		["st.voice_on"] = "Voice input on · press {0} again to stop",
		["st.voice_off"] = "Voice input stopped",
		["st.live_on"] = "Live caption on · press {0} again to stop",
		["st.live_off"] = "Live caption stopped",
		["st.http_ok"] = "HTTP API · http://{0}:{1}/api/ocr",
		["st.http_fail"] = "HTTP start failed: {0}",
		["st.http_init_fail"] = "HTTP init failed: {0}",
		["st.tray_fail"] = "Tray icon failed: {0}",
		["st.hotkey_fail"] = "Hotkey init failed: {0}",
		["st.hotkey_toggle_fail"] = "Hotkey toggle failed: {0}",
		["st.ocr_busy"] = "OCR in progress…",
		["st.clip_ocr"] = "Tray · clipboard OCR…",
		["st.clip_fail"] = "Clipboard OCR failed: {0}",
		["st.detlen"] = "Det side limit → {0} (next OCR)",
		["st.switched"] = "Switched · {0} · {1} · det {2}, loads on next OCR",
		["st.warmup"] = "{0} · warming up…",
		["st.warmup_ok"] = "{0} · ready · {1} · {2} · load {3}ms",
		["st.warmup_stay"] = "{0} · engine resident · {1} · {2}",
		["st.warmup_fail"] = "{0} · warmup failed: {1}",
		["st.sel_drag"] = "Selection · drag to expand · Ctrl+C",
		["st.sel_chars"] = "Selected {0} chars · Ctrl+C",
		["st.sel_all"] = "All {0} chars · Ctrl+C",
		["st.sel_clear"] = "Selection cleared",
		["st.no_text"] = "Nothing to copy",
		["st.copy_fail"] = "Copy failed: {0}",
		["st.snap_recopy_img"] = "Re-copied as image · {0}",
		["st.snap_recopy_file"] = "Re-copied as file · {0}",
		["st.snap_recopy_path"] = "Re-copied as path · {0}",
		["st.snap_recopy_none"] = "No screenshot to re-copy",
		["st.snap_recopy_fail"] = "Re-copy failed: {0}",
		["st.capture_cancel"] = "Capture cancelled",
		["st.capture_ocr"] = "Capture {0}×{1} · OCR…",
		["st.capture_fail"] = "Capture OCR failed: {0}",
		["st.record_opt"] = "Record options saved · {0}",
		["st.record_busy"] = "Wait for capture/record to finish",
		["st.record_pick"] = "Record · click window or drag region…",
		["st.record_cancel"] = "Record cancelled",
		["st.record_region"] = "Record {0}×{1} · {2} · {3}fps · {4}",
		["st.record_saved"] = "Record saved: {0}",
		["st.record_end"] = "Record ended (not saved)",
		["st.record_fail"] = "Record failed: {0}",
		["st.longshot"] = "Long shot · click target window…",
		["st.longshot_cancel"] = "Long shot cancelled",
		["st.lang"] = "UI language → {0}",
		["msg.capture"] = "Screenshot OCR",
		["msg.record"] = "Screen record",
		["msg.recordopt"] = "Record options",

		["tray.show"] = "Show main window",
		["tray.ocr"] = "Screenshot OCR",
		["tray.snap"] = "Screenshot annotate",
		["tray.board"] = "Screen board",
		["tray.voice"] = "Voice input",
		["tray.clip"] = "OCR from clipboard",
		["tray.clipfile"] = "Copy clipboard image as file",
		["tray.pdf"] = "PDF workbench…",
		["tray.snapshots"] = "Screenshot history",
		["tray.snapcopyimg"] = "On capture · copy as image",
		["tray.snapcopyfile"] = "On capture · copy as file",
		["tray.snapcopypath"] = "On capture · copy as file path",
		["tray.record"] = "Screen record",
		["tray.recordopt"] = "Record options…",
		["tray.gifrecord"] = "GIF record",
		["tray.gifrecordopt"] = "GIF record options…",
		["tray.settings"] = "Settings…",
		["tray.exit"] = "Exit",
		["tray.tip"] = "WpfOCR",

		["set.title"] = "Settings",
		["set.tab.general"] = "General",
		["set.tab.ocr"] = "OCR",
		["set.tab.hotkey"] = "Hotkeys",
		["set.tab.asr"] = "Speech",
		["set.tab.snap"] = "Capture",
		["set.tab.http"] = "API",
		["set.pack"] = "Model pack",
		["set.variant"] = "Language / variant",
		["set.device"] = "Device",
		["set.device.gpu"] = "GPU (NVIDIA CUDA)",
		["set.device.igpu"] = "iGPU (Intel DirectML)",
		["set.device.cpu"] = "CPU",
		["set.device.hint"] = "iGPU uses DirectML; cannot switch to CUDA in the same process — restart if needed",
		["set.detlen"] = "Det side limit",
		["set.detlen.hint"] = "Also switchable from the main window toolbar",
		["set.detth"] = "Det threshold",
		["set.boxth"] = "Box confidence",
		["set.cls"] = "Enable orientation classifier (cls)",
		["set.service"] = "Service mode (keep engine warm, do not unload)",
		["set.service.hint"] = "When on, load the engine at startup/after changes and keep it resident; when off, lazy-load (discard after changes, reload on next OCR)",
		["set.pdf"] = "PDF OCR",
		["set.pdf.text"] = "Add invisible text layer on export (searchable / copyable)",
		["set.pdf.hint"] = "Page size follows the original PDF; raster DPI is fixed (~150)",
		["set.hotkey"] = "Global hotkeys",
		["set.hotkey.hint"] = "Click Capture then press a combo; Clear disables the hotkey. Empty is also allowed.",
		["set.hotkey.main"] = "Show/hide main window · default Ctrl+Alt+O; empty = off",
		["set.hotkey.snap"] = "Annotate · default Ctrl+Alt+Q; empty = off",
		["set.hotkey.ocr"] = "Screenshot OCR · default Ctrl+Alt+W; empty = off",
		["set.hotkey.board"] = "Screen board · freeze & annotate · default empty = off",
		["set.hotkey.voice"] = "Voice input · dictation into focused window · default Ctrl+Alt+V; empty = off",
		["set.hotkey.live"] = "Live caption · desktop streaming subtitles · default Ctrl+Alt+B; empty = off",
		["set.lang"] = "UI language",
		["set.lang.hint"] = "Applies immediately and saves to config.toml",
		["set.tray"] = "Minimize to tray (closing asks to quit)",
		["set.log"] = "Diagnostics",
		["set.log.enable"] = "Write diagnostic logs (off by default)",
		["set.log.hint"] = "Writes log/capture.log and record log/record_*.log; leave off for daily use",
		["set.http"] = "HTTP OCR API (Umi-compatible)",
		["set.http.hint"] = "POST /api/ocr · JSON base64 or multipart; GET /api/ocr/get_options",
		["set.http.enable"] = "Enable HTTP API",
		["set.http.host"] = "Listen address",
		["set.http.port"] = "Port",
		["set.asr.mode"] = "Voice input model",
		["set.asr.mode.hint"] = "Streaming: words appear as you speak. Offline: record the whole take, recognize once when you stop. With auto-split, each sentence is polished and typed as soon as it is recognized.",
		["set.asr.mode.stream"] = "Streaming model (live)",
		["set.asr.mode.offline"] = "Offline model (output on stop)",
		["set.asr.voice.polish"] = "Polish voice input",
		["set.asr.voice.split"] = "Auto-split voice input sentences",
		["set.asr.voice.split.tip"] = "As soon as a sentence is recognized, polish (if enabled) and type it",
		["set.asr.voice.split.sec"] = "Auto-split interval (seconds)",
		["set.asr.voice.split.sec.tip"] = "Split only after this much silence; continuous speech is not cut; 1–30, default 5",
		["set.asr.live"] = "Live caption model",
		["set.asr.live.hint"] = "Streaming: captions appear as you speak. Offline: split on silence then recognize each utterance (more accurate, higher latency).",
		["set.asr.live.stream"] = "Streaming model",
		["set.asr.live.offline"] = "Offline model (split on silence)",
		["set.asr.live.polish"] = "Polish live captions",
		["set.asr.live.split"] = "Auto-split after polish",
		["set.asr.llm"] = "Polish (OpenAI-compatible)",
		["set.asr.llm.hint"] = "Requires the polish checkbox plus URL and model id. Voice input: at sentence end / stop. Live captions: after each sentence. Previous output in the same session is sent as context (about 1k chars) to fix homophones. Token may be empty for local servers.",
		["set.asr.llm.url"] = "API URL",
		["set.asr.llm.token"] = "Token",
		["set.asr.llm.model"] = "Model id",
		["set.asr.llm.prompt"] = "Polish prompt",
		["set.ok"] = "Save",
		["set.cancel"] = "Cancel",
	};
}
